config/routes.rb
Rails.application.routes.draw do
  resources :book_reviews
  get 'users/show'
  get "/" => "static_pages#home"
  resources :books
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    has_many :book_review, ->{ order('created_at DESC') }, :class_name => 'BookReview'
end

app/models/book_review.rb
class BookReview < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :image])
    end
end

app/controllers/book_reviews_controller.rb
class BookReviewsController < ApplicationController
  before_action :set_book_review, only: %i[ show edit update destroy ]

  # GET /book_reviews or /book_reviews.json
  def index
    @book_reviews = BookReview.all
  end

  # GET /book_reviews/1 or /book_reviews/1.json
  def show
  end

  # GET /book_reviews/new
  def new
    @book_review = BookReview.new
  end

  # GET /book_reviews/1/edit
  def edit
  end

  # POST /book_reviews or /book_reviews.json
  def create
    @book_review = BookReview.new(book_review_params)

    respond_to do |format|
      url = "/books/#{@book_review.book_id.to_s}"
      if @book_review.save
        format.html { redirect_to url, notice: "Book review was successfully created." }
        format.json { render :show, status: :created, location: @book_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_reviews/1 or /book_reviews/1.json
  def update
    respond_to do |format|
      if @book_review.update(book_review_params)
        format.html { redirect_to book_review_url(@book_review), notice: "Book review was successfully updated." }
        format.json { render :show, status: :ok, location: @book_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_reviews/1 or /book_reviews/1.json
  def destroy
    @book_review.destroy

    respond_to do |format|
      format.html { redirect_to book_reviews_url, notice: "Book review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_review
      @book_review = BookReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_review_params
      params.require(:book_review).permit(:user_id, :book_id, :review)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user! do |c|
    if !authenticate_user! 
      redirect_to "/"
    end
  end
  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
    @book_review = BookReview.new
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :number_of_pages, :image, :detail)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_reviews_helper.rb
module BookReviewsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_reviews/_book_review.html.erb
<div id="<%= dom_id book_review %>">
  <p>
    <strong>User:</strong>
    <%= book_review.user_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= book_review.book_id %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= book_review.review %>
  </p>

</div>

app/views/book_reviews/_form.html.erb
<%= form_with(model: book_review) do |form| %>
  <% if book_review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book_review.errors.count, "error") %> prohibited this book_review from being saved:</h2>

      <ul>
        <% book_review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.number_field :book_id %>
  </div>

  <div>
    <%= form.label :review, style: "display: block" %>
    <%= form.text_area :review %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/book_reviews/edit.html.erb
<h1>Editing book review</h1>

<%= render "form", book_review: @book_review %>

<br>

<div>
  <%= link_to "Show this book review", @book_review %> |
  <%= link_to "Back to book reviews", book_reviews_path %>
</div>

app/views/book_reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Book reviews</h1>

<div id="book_reviews">
  <% @book_reviews.each do |book_review| %>
    <%= render book_review %>
    <p>
      <%= link_to "Show this book review", book_review %>
    </p>
  <% end %>
</div>

<%= link_to "New book review", new_book_review_path %>

app/views/book_reviews/new.html.erb
<h1>New book review</h1>

<%= render "form", book_review: @book_review %>

<br>

<div>
  <%= link_to "Back to book reviews", book_reviews_path %>
</div>

app/views/book_reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_review %>

<div>
  <%= link_to "Edit this book review", edit_book_review_path(@book_review) %> |
  <%= link_to "Back to book reviews", book_reviews_path %>

  <%= button_to "Destroy this book review", @book_review, method: :delete %>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <div class="card" style="width: 18rem;">
    <% if book.image.attached? %>
      <%= image_tag (book.image), class: "card-img-top", style: "height: 9rem" %>
    <% else %>
      <%= image_tag "book.jpg", class: "card-img-top", style: "height: 9rem" %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title">Book title:</h5>
      <p class="card-text"><%= book.title ? book.title : "No title" %></p>
      <h5 class="card-title">Number of pages:</h5>
      <p class="card-text"><%= book.number_of_pages ? book.number_of_pages : "0" %></p>
      <h5 class="card-title">Book Detail</h5>
      <p class="card-text"> <%= book.detail ? book.detail : "No detail" %></p>
      <%= link_to "Show this book", book, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form|  %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :number_of_pages, style: "display: block" %>
    <%= form.number_field :number_of_pages, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :detail, style: "display: block" %>
    <%= form.text_area :detail, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :file, style: "display: block" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  
  <div class="form-group mt-3">
    <%= form.submit 'New book', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="text-align: center;">Books</h1>

<div id="books">
  <div class="container mh-100 mw-100 d-flex justify-content-center align-items-center">
    <% @books.each do |book| %>
        <%= render book %>
    <% end %>
  </div>
</div>
<div style="text-align: center;" class="mt-5">
  <%= link_to "New book", new_book_path, class: "btn btn-primary" %>
</div>

app/views/books/new.html.erb
<div class="container-fluid d-flex flex-column gap-2 w-5">
  <h1>New book</h1>
  <%= render "form", book: @book %>
</div>

<br>

<div style="text-align: center">
  <%= link_to "Back to books", books_path, class: "btn btn-primary" %>
</div>

app/views/books/show.html.erb
<div class="container-fluid d-flex flex-column gap-2">
  <div>
    <p style="color: green"><%= notice %></p>
  </div>

  <div class="d-flex gap-2">
    <%= render @book %>
    <div>
      <%= link_to "Edit this book", edit_book_path(@book), class: "btn btn-primary" %> |
      <%= link_to "Back to books", books_path, class: "btn btn-primary" %>

      <%= button_to "Destroy this book", @book, method: :delete, class: "btn btn-danger mt-5" %>
    </div>

    <%= form_with(model: @book_review) do |form| %>
      <h2>Review Form</h2>
      <div class="form-group">
        <%= form.label :review, style: "display: block" %>
        <%= form.text_area :review, class: "form-control" %>
        <%= form.hidden_field :user_id, :value => current_user.id %>
        <%= form.hidden_field :book_id, :value => @book.id %>
      </div>
      <div>
        <%= form.submit "Create book review", :class => "btn btn-primary mt-4" %>
      </div>
    <% end %>

    <h2>Review list</h2>
    <ul>
      <% @book.book_review.each do |book_review| %>
        <li><%= book_review.review %> (<i><%= book_review.user.name %></i>)</li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to  "Book Review", "/", class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if !current_user %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
        
        <% if current_user %>
          <% if current_user.image.attached %>
            <li class="nav-item">
              <%= link_to users_show_path, class: "nav-link" do %>
                <%= image_tag current_user.image, height: 27, width: 27 %>
              <% end%>
            </li>
          <% else %>
           <li class="nav-item">
            <%= link_to current_user.email, users_show_path, class: "nav-link" %>
           </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render  "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="container d-flex flex-column bd-highlight mb-3 mt-3 align-items-center p-5">
    <p class="text-muted display-5">Home page</p>

    <% if current_user %>
      <%= link_to user_signed_in? ? current_user.email : "", users_show_path, class: "btn btn-primary w-50" %>
    <% end %>
    
    <br>
    <%= link_to "Search book", books_path, class: "btn btn-primary w-50" %>
</div>

app/views/users/show.html.erb
<div class="container h-100 w-100 d-flex flex-column justify-content-center align-items-center">
    <div class="row">
        <h1 class="title">
            User information
        </div>
    </div>
    <div class="row w-60 h-75">
        <div class="col-md-4">
            <% if current_user.image.attached? %>
                <%= image_tag current_user.image , class: "w-100 h-100" %>
            <% else %>
                <%= image_tag "user.png" , class: "w-100 h-100" %>
            <% end %>
        </div>
        <div class="col-md-8 p-5">
            <div class="w-100 h2 mb-5">
                Name: <%= current_user.name ? current_user.name : "" %>
            </div>
            <div class="w-100 h2 mb-5">
                Age: <%= current_user.age ? current_user.age : "" %>
            </div>
            <div class="w-100 h2">
                Email: <%= current_user.email %>
            </div>
        </div>
    </div>
</div>